export const INFONAVIT_AUTO_DOCUMENT_TYPES = [
  "infonavit_carta_bajo_protesta",
  "infonavit_presupuesto_mejoramiento",
  "infonavit_solicitud_inscripcion",
] as const;

export type InfonavitAutoDocumentType =
  (typeof INFONAVIT_AUTO_DOCUMENT_TYPES)[number];

export const INFONAVIT_AUTO_DOCUMENT_LABELS: Record<
  InfonavitAutoDocumentType,
  string
> = {
  infonavit_carta_bajo_protesta: "Carta bajo protesta",
  infonavit_presupuesto_mejoramiento: "Presupuesto de mejoramiento",
  infonavit_solicitud_inscripcion: "Solicitud de inscripción de crédito",
};

export const INFONAVIT_AUTO_DOCUMENT_FILENAMES: Record<
  InfonavitAutoDocumentType,
  string
> = {
  infonavit_carta_bajo_protesta: "Carta Bajo Protesta.pdf",
  infonavit_presupuesto_mejoramiento: "Presupuesto de Mejoramiento.pdf",
  infonavit_solicitud_inscripcion: "Solicitud de Inscripción de Crédito.pdf",
};

export function isInfonavitAutoGeneratedDocumentType(
  value: string | null | undefined,
): value is InfonavitAutoDocumentType {
  return (INFONAVIT_AUTO_DOCUMENT_TYPES as readonly string[]).includes(
    String(value ?? ""),
  );
}

export function infonavitAutoDocumentLabel(tipo: string): string {
  if (isInfonavitAutoGeneratedDocumentType(tipo)) {
    return INFONAVIT_AUTO_DOCUMENT_LABELS[tipo];
  }
  return tipo;
}

export function infonavitAutoDocumentFilename(tipo: string): string {
  if (isInfonavitAutoGeneratedDocumentType(tipo)) {
    return INFONAVIT_AUTO_DOCUMENT_FILENAMES[tipo];
  }
  return "Documento INFONAVIT.pdf";
}
