import assert from "node:assert/strict";
import { describe, it } from "node:test";
import {
  INFONAVIT_AUTO_DOCUMENT_FILENAMES,
  INFONAVIT_AUTO_DOCUMENT_LABELS,
  INFONAVIT_AUTO_DOCUMENT_TYPES,
  infonavitAutoDocumentFilename,
  infonavitAutoDocumentLabel,
  isInfonavitAutoGeneratedDocumentType,
} from "./infonavit-auto-document-types";
import {
  CLIENTE_SOLICITUD_DOCUMENT_TIPO,
  INTEGRATION_DOC_TIPOS_ASESOR_ENVIO,
  INTEGRATION_DOC_TIPOS_ASESOR_UPLOAD,
  INTEGRATION_DOC_TIPOS_MESA_REGISTER,
  INTEGRATION_DOC_TIPOS_MESA_UPLOAD,
  INTEGRATION_DOC_TIPOS_OBLIGATORIOS,
  INTEGRATION_DOC_TIPOS_VALIDACION_MESA,
} from "./integration-docs-completos";
import { DOCUMENTO_CATALOGO_MAP, TIPO_DOCUMENTO_CATALOGO } from "./types";

describe("P189 B5 tipos INFONAVIT auto-generados", () => {
  it("son exactamente 3 tipos DB", () => {
    assert.deepEqual([...INFONAVIT_AUTO_DOCUMENT_TYPES], [
      "infonavit_carta_bajo_protesta",
      "infonavit_presupuesto_mejoramiento",
      "infonavit_solicitud_inscripcion",
    ]);
  });

  it("labels UI exactos y filenames genéricos sin PII", () => {
    assert.equal(
      INFONAVIT_AUTO_DOCUMENT_LABELS.infonavit_carta_bajo_protesta,
      "Carta bajo protesta",
    );
    assert.equal(
      INFONAVIT_AUTO_DOCUMENT_LABELS.infonavit_presupuesto_mejoramiento,
      "Presupuesto de mejoramiento",
    );
    assert.equal(
      INFONAVIT_AUTO_DOCUMENT_LABELS.infonavit_solicitud_inscripcion,
      "Solicitud de inscripción de crédito",
    );
    assert.equal(
      INFONAVIT_AUTO_DOCUMENT_FILENAMES.infonavit_carta_bajo_protesta,
      "Carta Bajo Protesta.pdf",
    );
    assert.equal(
      INFONAVIT_AUTO_DOCUMENT_FILENAMES.infonavit_presupuesto_mejoramiento,
      "Presupuesto de Mejoramiento.pdf",
    );
    assert.equal(
      INFONAVIT_AUTO_DOCUMENT_FILENAMES.infonavit_solicitud_inscripcion,
      "Solicitud de Inscripción de Crédito.pdf",
    );
    for (const tipo of INFONAVIT_AUTO_DOCUMENT_TYPES) {
      assert.equal(infonavitAutoDocumentLabel(tipo), INFONAVIT_AUTO_DOCUMENT_LABELS[tipo]);
      assert.equal(infonavitAutoDocumentFilename(tipo), INFONAVIT_AUTO_DOCUMENT_FILENAMES[tipo]);
      assert.doesNotMatch(infonavitAutoDocumentFilename(tipo), /nss|curp|rfc|@/i);
    }
  });

  it("están en el catálogo como sistema / opcional / sin etapa", () => {
    for (const tipo of INFONAVIT_AUTO_DOCUMENT_TYPES) {
      assert.equal(isInfonavitAutoGeneratedDocumentType(tipo), true);
    assert.ok(TIPO_DOCUMENTO_CATALOGO.includes(tipo as (typeof TIPO_DOCUMENTO_CATALOGO)[number]));
      const item = DOCUMENTO_CATALOGO_MAP[tipo];
      assert.equal(item.ownerRole, "sistema");
      assert.equal(item.obligatorio, "opcional");
      assert.deepEqual([...item.etapasRequeridas], []);
    }
    assert.equal(isInfonavitAutoGeneratedDocumentType(CLIENTE_SOLICITUD_DOCUMENT_TIPO), false);
    assert.equal(isInfonavitAutoGeneratedDocumentType("cliente_solicitud"), false);
  });

  it("no entran a allowlists de upload/envio/obligatorios/mesa", () => {
    const allowlists = [
      INTEGRATION_DOC_TIPOS_ASESOR_ENVIO,
      INTEGRATION_DOC_TIPOS_ASESOR_UPLOAD,
      INTEGRATION_DOC_TIPOS_OBLIGATORIOS,
      INTEGRATION_DOC_TIPOS_VALIDACION_MESA,
      INTEGRATION_DOC_TIPOS_MESA_UPLOAD,
      INTEGRATION_DOC_TIPOS_MESA_REGISTER,
    ];
    for (const tipo of INFONAVIT_AUTO_DOCUMENT_TYPES) {
      for (const list of allowlists) {
        assert.equal(
          (list as readonly string[]).includes(tipo),
          false,
          `${tipo} no debe estar en allowlist`,
        );
      }
    }
  });
});
