/**
 * Política P189 DOCX bajo demanda (Mesa-only).
 * Sin PII. Sin Storage. Sin segundo mapping.
 */

import { z } from "zod";
import {
  INFONAVIT_AUTO_DOCUMENT_DOCX_FILENAMES,
  isInfonavitAutoGeneratedDocumentType,
} from "./infonavit-auto-document-types";
import {
  INFONAVIT_DB_TO_B1,
  isInfonavitDbDocumentType,
  type InfonavitDbDocumentType,
} from "../../../supabase/functions/_shared/infonavit-pdf/document-type-map.ts";
import type { InfonavitDocumentType } from "../../../supabase/functions/_shared/infonavit-pdf/types.ts";

export const infonavitDocxRequestSchema = z.object({
  expedienteId: z.string().uuid(),
  documentType: z.enum([
    "infonavit_carta_bajo_protesta",
    "infonavit_presupuesto_mejoramiento",
    "infonavit_solicitud_inscripcion",
  ]),
  submissionVersion: z.union([
    z.number().int().nonnegative(),
    z.string().regex(/^\d+$/),
  ]),
});

export type InfonavitDocxRequest = z.infer<typeof infonavitDocxRequestSchema>;

export const INFONAVIT_DOCX_MIME =
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document";

export const INFONAVIT_DOCX_MESA_ROLES = [
  "mesa_admin",
  "mesa_interno",
  "mesa_externo",
  "super_admin",
] as const;

export type InfonavitDocxMesaRole = (typeof INFONAVIT_DOCX_MESA_ROLES)[number];

export const INFONAVIT_DOCX_FILENAMES: Record<InfonavitDbDocumentType, string> =
  INFONAVIT_AUTO_DOCUMENT_DOCX_FILENAMES;

export type InfonavitDocxDenyCode =
  | "unauthenticated"
  | "forbidden"
  | "invalid_request"
  | "not_done"
  | "version_mismatch"
  | "snapshot_missing";

export type InfonavitDocxDecision =
  | {
      ok: true;
      documentType: InfonavitDbDocumentType;
      b1Type: InfonavitDocumentType;
      filename: string;
      submissionVersion: number;
    }
  | {
      ok: false;
      httpStatus: 400 | 401 | 403 | 404 | 409;
      code: InfonavitDocxDenyCode;
      message: string;
    };

const PUBLIC_MESSAGE: Record<InfonavitDocxDenyCode, string> = {
  unauthenticated: "No hay sesión activa.",
  forbidden: "No se puede descargar el Word editable.",
  invalid_request: "Solicitud inválida.",
  not_done: "El documento PDF aún no está listo.",
  version_mismatch: "La versión solicitada no coincide.",
  snapshot_missing: "No se encontró el documento editable.",
};

export function infonavitDocxPublicMessage(code: InfonavitDocxDenyCode): string {
  return PUBLIC_MESSAGE[code];
}

export function isMesaInfonavitDocxRole(
  role: string | null | undefined,
): role is InfonavitDocxMesaRole {
  return (INFONAVIT_DOCX_MESA_ROLES as readonly string[]).includes(
    String(role ?? "").trim(),
  );
}

export function infonavitDocxFilename(tipo: string): string {
  if (isInfonavitAutoGeneratedDocumentType(tipo)) {
    return INFONAVIT_DOCX_FILENAMES[tipo];
  }
  return "Documento INFONAVIT editable.docx";
}

export function parseSubmissionVersion(raw: unknown): number | null {
  if (typeof raw === "number" && Number.isInteger(raw) && raw >= 0) return raw;
  if (typeof raw === "string" && /^\d+$/.test(raw.trim())) {
    return Number(raw.trim());
  }
  return null;
}

export function authorizeInfonavitDocxDownload(args: {
  authenticated: boolean;
  appRole: string | null;
  active: boolean;
  canSeeExpediente: boolean;
  aplica: boolean;
  hasSubmission: boolean;
  estadoSubmissionVersion: number | null;
  requestedSubmissionVersion: unknown;
  documentType: string;
  documentStatus: string | null;
}): InfonavitDocxDecision {
  if (!args.authenticated) {
    return {
      ok: false,
      httpStatus: 401,
      code: "unauthenticated",
      message: PUBLIC_MESSAGE.unauthenticated,
    };
  }
  if (!args.active || !isMesaInfonavitDocxRole(args.appRole)) {
    return {
      ok: false,
      httpStatus: 403,
      code: "forbidden",
      message: PUBLIC_MESSAGE.forbidden,
    };
  }
  if (!args.canSeeExpediente) {
    return {
      ok: false,
      httpStatus: 403,
      code: "forbidden",
      message: PUBLIC_MESSAGE.forbidden,
    };
  }
  if (!isInfonavitDbDocumentType(args.documentType)) {
    return {
      ok: false,
      httpStatus: 400,
      code: "invalid_request",
      message: PUBLIC_MESSAGE.invalid_request,
    };
  }
  const requested = parseSubmissionVersion(args.requestedSubmissionVersion);
  if (requested === null) {
    return {
      ok: false,
      httpStatus: 400,
      code: "invalid_request",
      message: PUBLIC_MESSAGE.invalid_request,
    };
  }
  if (!args.aplica || !args.hasSubmission || args.estadoSubmissionVersion === null) {
    return {
      ok: false,
      httpStatus: 404,
      code: "snapshot_missing",
      message: PUBLIC_MESSAGE.snapshot_missing,
    };
  }
  if (requested !== args.estadoSubmissionVersion) {
    return {
      ok: false,
      httpStatus: 409,
      code: "version_mismatch",
      message: PUBLIC_MESSAGE.version_mismatch,
    };
  }
  if (args.documentStatus !== "done") {
    return {
      ok: false,
      httpStatus: 409,
      code: "not_done",
      message: PUBLIC_MESSAGE.not_done,
    };
  }
  return {
    ok: true,
    documentType: args.documentType,
    b1Type: INFONAVIT_DB_TO_B1[args.documentType],
    filename: INFONAVIT_DOCX_FILENAMES[args.documentType],
    submissionVersion: requested,
  };
}
