import assert from "node:assert/strict";
import { describe, it } from "node:test";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { mapSupabaseRowToExpedienteArchivoListItem } from "./map-supabase-expediente-documentos";
import { INFONAVIT_AUTO_DOCUMENT_TYPES } from "./infonavit-auto-document-types";
import { shouldShowInfonavitPdfSection } from "./infonavit-pdf-estado";

function baseRow(tipo: string) {
  return {
    id: `id-${tipo}`,
    expediente_id: "exp-1",
    tipo_documento: tipo,
    nombre_original: `${tipo}.pdf`,
    mime_type: "application/pdf",
    size_bytes: 10,
    estatus_revision: "subido",
    comentario_mesa: null,
    uploaded_by_role: "sistema",
    created_at: "2026-08-17T12:00:00.000Z",
  };
}

describe("P189 B5 aislamiento de listados genéricos", () => {
  it("mapper omite los 3 tipos auto para no duplicar en listas genéricas", () => {
    for (const tipo of INFONAVIT_AUTO_DOCUMENT_TYPES) {
      assert.equal(mapSupabaseRowToExpedienteArchivoListItem(baseRow(tipo)), null);
    }
    assert.ok(
      mapSupabaseRowToExpedienteArchivoListItem(baseRow("cliente_ine_frente")),
    );
  });

  it("legacy y non-Mejoravit no disparan sección P189", () => {
    assert.equal(
      shouldShowInfonavitPdfSection({ aplica: false, has_submission: false }),
      false,
    );
    assert.equal(
      shouldShowInfonavitPdfSection({ aplica: true, has_submission: false }),
      false,
    );
  });

  it("supabase.repo filtra P189 del resumen y rechaza upload", () => {
    const repoSrc = readFileSync(
      join(process.cwd(), "src/domain/expediente-archivos/supabase.repo.ts"),
      "utf8",
    );
    assert.match(repoSrc, /isInfonavitAutoGeneratedDocumentType/);
    assert.match(repoSrc, /Este documento lo genera el sistema/);
    const mockSrc = readFileSync(
      join(process.cwd(), "src/domain/expediente-archivos/mock-indexeddb.repo.ts"),
      "utf8",
    );
    assert.match(mockSrc, /isInfonavitAutoGeneratedDocumentType\(tipo\)/);
  });
});
