import {
  INFONAVIT_AUTO_DOCUMENT_TYPES,
  infonavitAutoDocumentFilename,
  infonavitAutoDocumentLabel,
  isInfonavitAutoGeneratedDocumentType,
  type InfonavitAutoDocumentType,
} from "./infonavit-auto-document-types";

export const INFONAVIT_PDF_ESTADO_POLL_MS = 10_000;

export type InfonavitPdfOutboxUiStatus =
  | "pending"
  | "processing"
  | "done"
  | "failed";

export type InfonavitPdfDocumentoMeta = Readonly<{
  id: string;
  tipo_documento: string;
  nombre_original: string | null;
  mime_type: string | null;
  size_bytes: number | null;
  version: number | null;
  created_at: string | null;
}>;

export type InfonavitPdfDocumentEstado = Readonly<{
  document_type: InfonavitAutoDocumentType;
  status: InfonavitPdfOutboxUiStatus;
  latest_document: InfonavitPdfDocumentoMeta | null;
  previous_document: InfonavitPdfDocumentoMeta | null;
}>;

export type InfonavitPdfEstado = Readonly<{
  aplica: boolean;
  has_submission: boolean;
  submission_version: number | null;
  submission_kind: string | null;
  documents: readonly InfonavitPdfDocumentEstado[];
}>;

const PII_FORBIDDEN_KEYS = [
  "nss",
  "curp",
  "rfc",
  "celular",
  "telefono",
  "correo",
  "direccion",
  "payload",
  "snapshot_hash",
  "template_sha256",
  "last_error_code",
  "uploaded_by",
  "worker_secret",
  "attempts",
] as const;

export function infonavitPdfUiStatusLabel(
  status: InfonavitPdfOutboxUiStatus,
): string {
  if (status === "done") return "Listo";
  if (status === "failed") return "Error de generación";
  return "Generando";
}

export function infonavitPdfEstadoNeedsPoll(
  estado: InfonavitPdfEstado | null | undefined,
): boolean {
  if (!estado?.aplica || !estado.has_submission) return false;
  return estado.documents.some(
    (d) => d.status === "pending" || d.status === "processing",
  );
}

export function shouldShowInfonavitPdfSection(args: {
  aplica: boolean;
  has_submission: boolean;
  submittedToMesa?: boolean;
  requireSubmitted?: boolean;
}): boolean {
  if (!args.aplica || !args.has_submission) return false;
  if (args.requireSubmitted && !args.submittedToMesa) return false;
  return true;
}

export function parseInfonavitPdfDocumentoMeta(
  raw: unknown,
): InfonavitPdfDocumentoMeta | null {
  if (!raw || typeof raw !== "object") return null;
  const o = raw as Record<string, unknown>;
  const id = typeof o.id === "string" ? o.id.trim() : "";
  if (!id) return null;
  return {
    id,
    tipo_documento: typeof o.tipo_documento === "string" ? o.tipo_documento : "",
    nombre_original:
      typeof o.nombre_original === "string" ? o.nombre_original : null,
    mime_type: typeof o.mime_type === "string" ? o.mime_type : null,
    size_bytes: typeof o.size_bytes === "number" ? o.size_bytes : null,
    version: typeof o.version === "number" ? o.version : null,
    created_at: typeof o.created_at === "string" ? o.created_at : null,
  };
}

function parseStatus(raw: unknown): InfonavitPdfOutboxUiStatus {
  if (raw === "done" || raw === "failed" || raw === "processing") return raw;
  return "pending";
}

export function parseInfonavitPdfEstado(raw: unknown): InfonavitPdfEstado {
  if (!raw || typeof raw !== "object") {
    return {
      aplica: false,
      has_submission: false,
      submission_version: null,
      submission_kind: null,
      documents: [],
    };
  }
  const o = raw as Record<string, unknown>;
  const aplica = o.aplica === true;
  const has_submission = o.has_submission === true;
  const docsRaw = Array.isArray(o.documents) ? o.documents : [];
  const byTipo = new Map<string, InfonavitPdfDocumentEstado>();
  for (const item of docsRaw) {
    if (!item || typeof item !== "object") continue;
    const d = item as Record<string, unknown>;
    const tipo = String(d.document_type ?? "");
    if (!isInfonavitAutoGeneratedDocumentType(tipo)) continue;
    byTipo.set(tipo, {
      document_type: tipo,
      status: parseStatus(d.status),
      latest_document: parseInfonavitPdfDocumentoMeta(d.latest_document),
      previous_document: parseInfonavitPdfDocumentoMeta(d.previous_document),
    });
  }
  const documents = INFONAVIT_AUTO_DOCUMENT_TYPES.map((tipo) => {
    return (
      byTipo.get(tipo) ?? {
        document_type: tipo,
        status: "pending" as const,
        latest_document: null,
        previous_document: null,
      }
    );
  });
  return {
    aplica,
    has_submission,
    submission_version:
      typeof o.submission_version === "number" ? o.submission_version : null,
    submission_kind:
      typeof o.submission_kind === "string" ? o.submission_kind : null,
    documents: aplica && has_submission ? documents : [],
  };
}

export function infonavitPdfEstadoJsonHasForbiddenKeys(json: string): boolean {
  const lower = json.toLowerCase();
  return PII_FORBIDDEN_KEYS.some((k) => lower.includes(`"${k}"`));
}

export function displayNameForInfonavitPdfDoc(
  tipo: string,
  meta: InfonavitPdfDocumentoMeta | null,
): string {
  const fromMeta = meta?.nombre_original?.trim();
  if (fromMeta) return fromMeta;
  return infonavitAutoDocumentFilename(tipo);
}

export function startInfonavitPdfEstadoPolling<T>(args: {
  enabled: boolean;
  needsPoll: boolean;
  onTick: () => void;
  intervalMs?: number;
  setIntervalFn: (handler: () => void, ms: number) => T;
  clearIntervalFn: (id: T) => void;
}): () => void {
  if (!args.enabled || !args.needsPoll) return () => {};
  const ms = args.intervalMs ?? INFONAVIT_PDF_ESTADO_POLL_MS;
  const timer = args.setIntervalFn(() => {
    args.onTick();
  }, ms);
  return () => args.clearIntervalFn(timer);
}

export { infonavitAutoDocumentLabel, infonavitAutoDocumentFilename };
