#!/usr/bin/env bash
set -euo pipefail

DB_HOST="${SUPABASE_DB_HOST:-127.0.0.1}"
DB_PORT="${SUPABASE_DB_PORT:-54322}"
DB_USER="${SUPABASE_DB_USER:-postgres}"
DB_PASSWORD="${SUPABASE_DB_PASSWORD:-postgres}"
DB_NAME="${SUPABASE_DB_NAME:-postgres}"

run_sql_test() {
  local file="$1"
  echo "==> Running ${file}"
  PGPASSWORD="$DB_PASSWORD" psql \
    -v ON_ERROR_STOP=1 \
    -h "$DB_HOST" \
    -p "$DB_PORT" \
    -U "$DB_USER" \
    -d "$DB_NAME" \
    -f "$file"
}

run_sql_test "supabase/tests/rls_policies.sql"
run_sql_test "supabase/tests/audit_document_history.sql"
run_sql_test "supabase/tests/rpc_documento_revision.sql"
run_sql_test "supabase/tests/rpc_update_cliente_datos_revision.sql"
run_sql_test "supabase/tests/rpc_register_mesa_documento.sql"
run_sql_test "supabase/tests/rpc_mesa_pagare_expediente.sql"
run_sql_test "supabase/tests/rpc_mesa_notificacion_documento_expediente.sql"
run_sql_test "supabase/tests/rpc_mesa_solicitud_documento_expediente.sql"
run_sql_test "supabase/tests/mesa_complementarios_opcionales.sql"
run_sql_test "supabase/tests/documentos_obligatorios_roles.sql"
run_sql_test "supabase/tests/cliente_carta_empresa_opcional.sql"
run_sql_test "supabase/tests/cliente_acta_nacimiento_digital_opcional.sql"
run_sql_test "supabase/tests/cliente_notificacion_apodaca_opcional.sql"
run_sql_test "supabase/tests/carta_empresa_image_mime.sql"
run_sql_test "supabase/tests/rpc_correcciones_asesor_post_mesa.sql"
run_sql_test "supabase/tests/rpc_enviar_a_mesa.sql"
run_sql_test "supabase/tests/rpc_asesor_update_monto_aprobado.sql"
run_sql_test "supabase/tests/rpc_register_expediente_documento.sql"
run_sql_test "supabase/tests/rpc_register_expediente_documento_retencion.sql"
run_sql_test "supabase/tests/rpc_avanzar_etapa_operativa.sql"
run_sql_test "supabase/tests/rpc_book_biometricos.sql"
run_sql_test "supabase/tests/rpc_avanzar_etapa_4_5.sql"
run_sql_test "supabase/tests/rpc_biometricos_cancel_reagendar.sql"
run_sql_test "supabase/tests/rpc_upsert_editor_decision.sql"
run_sql_test "supabase/tests/rpc_p081_canonical_approval.sql"
run_sql_test "supabase/tests/rpc_save_cliente_datos.sql"
run_sql_test "supabase/tests/rpc_mejoravit_base_cobro.sql"
run_sql_test "supabase/tests/rpc_mesa_monto_mejoravit_actualizado.sql"
run_sql_test "supabase/tests/rpc_cliente_datos_nombre_domicilio_opcional.sql"
run_sql_test "supabase/tests/rpc_cliente_datos_monto_calculado_editable.sql"
run_sql_test "supabase/tests/rpc_get_asesor_display_batch.sql"
run_sql_test "supabase/tests/rpc_get_asesor_agenda_calendar.sql"
run_sql_test "supabase/tests/rpc_get_mesa_agenda_bookings.sql"
run_sql_test "supabase/tests/rpc_mesa_reagendar_agenda_bookings.sql"
run_sql_test "supabase/tests/rpc_mesa_agenda_drive_validation.sql"
run_sql_test "supabase/tests/rpc_mesa_agenda_report_group.sql"
run_sql_test "supabase/tests/rpc_convert_biometricos_to_notificacion.sql"
run_sql_test "supabase/tests/rpc_rechazar_etapa_operativa.sql"
run_sql_test "supabase/tests/rpc_rechazo_reactivacion_p108a.sql"
run_sql_test "supabase/tests/rpc_cancelar_expediente_operativo.sql"
run_sql_test "supabase/tests/rpc_reingreso_post_biometricos.sql"
run_sql_test "supabase/tests/rpc_mesa_mover_etapa_operativa.sql"
run_sql_test "supabase/tests/rpc_mesa_gestion_firmas.sql"
run_sql_test "supabase/tests/agenda_config_biometricos_rules.sql"
run_sql_test "supabase/tests/rpc_upsert_agenda_config_biometricos.sql"
run_sql_test "supabase/tests/rpc_upsert_agenda_config_firmas.sql"
run_sql_test "supabase/tests/rpc_avanzar_etapa_2_3_4.sql"
run_sql_test "supabase/tests/rpc_avanzar_etapa_5_6.sql"
run_sql_test "supabase/tests/rpc_avanzar_etapa_6_7.sql"
run_sql_test "supabase/tests/rpc_avanzar_etapa_7_8.sql"
run_sql_test "supabase/tests/rpc_enviar_retencion_mesa.sql"
run_sql_test "supabase/tests/rpc_avanzar_etapa_8_9.sql"
run_sql_test "supabase/tests/rpc_backfill_retencion_p080.sql"
run_sql_test "supabase/tests/rpc_book_firmas.sql"
run_sql_test "supabase/tests/rpc_firmas_cancel_reagendar.sql"
run_sql_test "supabase/tests/rpc_avanzar_etapa_9_10.sql"
run_sql_test "supabase/tests/backfill_agenda_config_firmas.sql"
run_sql_test "supabase/tests/rpc_create_expediente.sql"
run_sql_test "supabase/tests/rpc_nss_lock_after_mesa.sql"
run_sql_test "supabase/tests/mesa_expediente_ops_backfill.sql"
run_sql_test "supabase/tests/mesa_expediente_ops_rls.sql"
run_sql_test "supabase/tests/rpc_mesa_take_release.sql"
run_sql_test "supabase/tests/admin_no_cumple_at_backfill.sql"
run_sql_test "supabase/tests/admin_repair_corrupt_monto_snapshots.sql"
run_sql_test "supabase/tests/admin_list_production_by_asesor_filter.sql"
run_sql_test "supabase/tests/admin_monto_aprobado_mejoravit_cap_aggregate.sql"
run_sql_test "supabase/tests/admin_estado_rechazados_cancelados.sql"
run_sql_test "supabase/tests/admin_report_expedientes_asesores_etapas.sql"
run_sql_test "supabase/tests/expediente_paso_visual_tracking_report_v2.sql"
run_sql_test "supabase/tests/admin_report_expedientes_asesores_etapas_v3.sql"
run_sql_test "supabase/tests/admin_mesa_correcciones_por_elemento.sql"
run_sql_test "supabase/tests/admin_mesa_timeline_pagination.sql"
run_sql_test "supabase/tests/rpc_mesa_list_bandeja_page.sql"
run_sql_test "supabase/tests/rpc_agenda_slot_capacities.sql"
run_sql_test "supabase/tests/rpc_agenda_capacity_by_time_p123.sql"
run_sql_test "supabase/tests/rpc_agenda_explicit_hourly_p124.sql"

echo "SQL tests: ALL PASSED"
