#!/usr/bin/env bash
set -euo pipefail

DB_HOST="${SUPABASE_DB_HOST:-127.0.0.1}"
DB_PORT="${SUPABASE_DB_PORT:-54322}"
DB_USER="${SUPABASE_DB_USER:-postgres}"
DB_PASSWORD="${SUPABASE_DB_PASSWORD:-postgres}"
DB_NAME="${SUPABASE_DB_NAME:-postgres}"

run_sql_test() {
  local file="$1"
  echo "==> Running ${file}"
  PGPASSWORD="$DB_PASSWORD" psql \
    -v ON_ERROR_STOP=1 \
    -h "$DB_HOST" \
    -p "$DB_PORT" \
    -U "$DB_USER" \
    -d "$DB_NAME" \
    -f "$file"
}

run_sql_test "supabase/tests/rls_policies.sql"
run_sql_test "supabase/tests/audit_document_history.sql"
run_sql_test "supabase/tests/rpc_documento_revision.sql"
run_sql_test "supabase/tests/rpc_update_cliente_datos_revision.sql"
run_sql_test "supabase/tests/rpc_register_mesa_documento.sql"
run_sql_test "supabase/tests/rpc_mesa_pagare_expediente.sql"
run_sql_test "supabase/tests/rpc_mesa_notificacion_documento_expediente.sql"
run_sql_test "supabase/tests/rpc_mesa_solicitud_documento_expediente.sql"
run_sql_test "supabase/tests/mesa_complementarios_opcionales.sql"
run_sql_test "supabase/tests/documentos_obligatorios_roles.sql"
run_sql_test "supabase/tests/cliente_carta_empresa_opcional.sql"
run_sql_test "supabase/tests/cliente_acta_nacimiento_digital_opcional.sql"
run_sql_test "supabase/tests/cliente_notificacion_apodaca_opcional.sql"
run_sql_test "supabase/tests/rpc_cliente_vigencia_derechos_opcional.sql"
run_sql_test "supabase/tests/rpc_cliente_constancia_situacion_fiscal_opcional.sql"
run_sql_test "supabase/tests/rpc_documento_tipo_scope_equipo.sql"
run_sql_test "supabase/tests/rpc_asesor_tipos_documento_visibles.sql"
run_sql_test "supabase/tests/rpc_asesor_en_equipo_por_lider_email.sql"
run_sql_test "supabase/tests/notificacion_apodaca_mime_pdf_jpeg_png.sql"
run_sql_test "supabase/tests/notificacion_apodaca_compartida_sin_gate_etapa.sql"
run_sql_test "supabase/tests/carta_empresa_image_mime.sql"
run_sql_test "supabase/tests/rpc_correcciones_asesor_post_mesa.sql"
run_sql_test "supabase/tests/rpc_enviar_a_mesa.sql"
run_sql_test "supabase/tests/rpc_asesor_enviar_reingreso_a_mesa.sql"
run_sql_test "supabase/tests/rpc_reingreso_edicion_completa.sql"
run_sql_test "supabase/tests/rpc_reingreso_cliente_datos_primer_alta.sql"
run_sql_test "supabase/tests/rpc_asesor_update_monto_aprobado.sql"
run_sql_test "supabase/tests/rpc_register_expediente_documento.sql"
run_sql_test "supabase/tests/rpc_register_expediente_documento_retencion.sql"
run_sql_test "supabase/tests/rpc_avanzar_etapa_operativa.sql"
run_sql_test "supabase/tests/rpc_book_biometricos.sql"
run_sql_test "supabase/tests/rpc_avanzar_etapa_4_5.sql"
run_sql_test "supabase/tests/rpc_biometricos_cancel_reagendar.sql"
run_sql_test "supabase/tests/rpc_upsert_editor_decision.sql"
run_sql_test "supabase/tests/rpc_p081_canonical_approval.sql"
run_sql_test "supabase/tests/rpc_save_cliente_datos.sql"
run_sql_test "supabase/tests/rpc_mejoravit_base_cobro.sql"
run_sql_test "supabase/tests/rpc_mesa_monto_mejoravit_actualizado.sql"
run_sql_test "supabase/tests/rpc_cliente_datos_nombre_domicilio_opcional.sql"
run_sql_test "supabase/tests/rpc_cliente_datos_monto_calculado_editable.sql"
run_sql_test "supabase/tests/rpc_get_asesor_display_batch.sql"
run_sql_test "supabase/tests/rpc_get_asesor_agenda_calendar.sql"
run_sql_test "supabase/tests/rpc_get_mesa_agenda_bookings.sql"
run_sql_test "supabase/tests/rpc_mesa_reagendar_agenda_bookings.sql"
run_sql_test "supabase/tests/rpc_mesa_agenda_drive_validation.sql"
run_sql_test "supabase/tests/rpc_mesa_agenda_report_group.sql"
run_sql_test "supabase/tests/rpc_convert_biometricos_to_notificacion.sql"
run_sql_test "supabase/tests/rpc_rechazar_etapa_operativa.sql"
run_sql_test "supabase/tests/rpc_rechazo_reactivacion_p108a.sql"
run_sql_test "supabase/tests/rpc_mesa_advance_manual_from_rejection_p204d.sql"
run_sql_test "supabase/tests/rpc_mesa_bandeja_counts_fast_p205.sql"
run_sql_test "supabase/tests/rpc_cancelar_expediente_operativo.sql"
run_sql_test "supabase/tests/rpc_reingreso_post_biometricos.sql"
run_sql_test "supabase/tests/rpc_mesa_mover_etapa_operativa.sql"
run_sql_test "supabase/tests/rpc_mesa_gestion_firmas.sql"
run_sql_test "supabase/tests/agenda_config_biometricos_rules.sql"
run_sql_test "supabase/tests/rpc_upsert_agenda_config_biometricos.sql"
run_sql_test "supabase/tests/rpc_upsert_agenda_config_firmas.sql"
run_sql_test "supabase/tests/rpc_avanzar_etapa_2_3_4.sql"
run_sql_test "supabase/tests/rpc_avanzar_etapa_5_6.sql"
run_sql_test "supabase/tests/rpc_avanzar_etapa_6_7.sql"
run_sql_test "supabase/tests/rpc_avanzar_etapa_7_8.sql"
run_sql_test "supabase/tests/rpc_enviar_retencion_mesa.sql"
run_sql_test "supabase/tests/rpc_avanzar_etapa_8_9.sql"
run_sql_test "supabase/tests/rpc_backfill_retencion_p080.sql"
run_sql_test "supabase/tests/rpc_book_firmas.sql"
run_sql_test "supabase/tests/rpc_firmas_cancel_reagendar.sql"
run_sql_test "supabase/tests/rpc_avanzar_etapa_9_10.sql"
run_sql_test "supabase/tests/backfill_agenda_config_firmas.sql"
run_sql_test "supabase/tests/rpc_create_expediente.sql"
run_sql_test "supabase/tests/rpc_nss_lock_after_mesa.sql"
run_sql_test "supabase/tests/mesa_expediente_ops_backfill.sql"
run_sql_test "supabase/tests/mesa_expediente_ops_rls.sql"
run_sql_test "supabase/tests/rpc_mesa_take_release.sql"
run_sql_test "supabase/tests/admin_no_cumple_at_backfill.sql"
run_sql_test "supabase/tests/admin_repair_corrupt_monto_snapshots.sql"
run_sql_test "supabase/tests/admin_list_production_by_asesor_filter.sql"
run_sql_test "supabase/tests/admin_monto_aprobado_mejoravit_cap_aggregate.sql"
run_sql_test "supabase/tests/admin_estado_rechazados_cancelados.sql"
run_sql_test "supabase/tests/admin_expedientes_snapshot_etapas.sql"
run_sql_test "supabase/tests/admin_report_expedientes_asesores_etapas.sql"
run_sql_test "supabase/tests/expediente_paso_visual_tracking_report_v2.sql"
run_sql_test "supabase/tests/admin_report_expedientes_asesores_etapas_v3.sql"
run_sql_test "supabase/tests/admin_mesa_correcciones_por_elemento.sql"
run_sql_test "supabase/tests/admin_mesa_timeline_pagination.sql"
run_sql_test "supabase/tests/rpc_mesa_list_bandeja_page.sql"
run_sql_test "supabase/tests/rpc_agenda_slot_capacities.sql"
run_sql_test "supabase/tests/rpc_agenda_capacity_by_time_p123.sql"
run_sql_test "supabase/tests/rpc_agenda_explicit_hourly_p124.sql"
run_sql_test "supabase/tests/rpc_agenda_capacity_update_safety_p125.sql"
run_sql_test "supabase/tests/rpc_agenda_allow_zero_recurring_capacity_p126.sql"
run_sql_test "supabase/tests/rpc_mesa_actividad_p127.sql"
run_sql_test "supabase/tests/rpc_mesa_presencia_p128.sql"
run_sql_test "supabase/tests/rpc_asesor_cambios_p130.sql"
run_sql_test "supabase/tests/rpc_asesor_cambios_p130_empty_batch.sql"
run_sql_test "supabase/tests/rpc_notificacion_libera_firma_p132.sql"
run_sql_test "supabase/tests/rpc_acuse_libera_firma_p132.sql"
run_sql_test "supabase/tests/rpc_firmas_sin_minimo_5_dias_habiles.sql"
run_sql_test "supabase/tests/rpc_register_retencion_p117.sql"
run_sql_test "supabase/tests/rpc_cliente_datos_field_formats_p133.sql"
run_sql_test "supabase/tests/rpc_cliente_datos_telefonos_unicos_p189.sql"
run_sql_test "supabase/tests/rpc_infonavit_submission_snapshot_p189.sql"
run_sql_test "supabase/tests/rpc_p189_snapshot_monto_aprobado.sql"
run_sql_test "supabase/tests/rpc_p189_parse_direccion_parity.sql"
run_sql_test "supabase/tests/rpc_infonavit_pdf_worker_p189_b4.sql"
run_sql_test "supabase/tests/rpc_infonavit_pdf_dispatch_p189_b41.sql"
run_sql_test "supabase/tests/rpc_infonavit_pdf_estado_p189_b5.sql"
run_sql_test "supabase/tests/rpc_infonavit_feature_flag_p189_b7.sql"
run_sql_test "supabase/tests/rpc_agenda_sheet_sync.sql"
run_sql_test "supabase/tests/rpc_agenda_sheet_reschedule_clear_prior_p160.sql"
run_sql_test "supabase/tests/rpc_agenda_booking_sheet_sync_status_p200.sql"
run_sql_test "supabase/tests/rpc_asesor_reprecalificar_nss_propio_mesa.sql"
run_sql_test "supabase/tests/rpc_asesor_reprecal_pre_mesa_p169.sql"
run_sql_test "supabase/tests/rpc_asesor_inbox_page_p161.sql"
run_sql_test "supabase/tests/rpc_asesor_equipo_lider_silvia.sql"
run_sql_test "supabase/tests/rpc_asesor_integrate_for_any_p208.sql"
run_sql_test "supabase/tests/rpc_asesor_tareas_terminales_p191.sql"
run_sql_test "supabase/tests/rpc_correcciones_enviadas_p130_mesa_p192.sql"
run_sql_test "supabase/tests/rpc_mesa_cambios_revision_origen_p193.sql"
run_sql_test "supabase/tests/rpc_mesa_cambios_detalle_p194.sql"
run_sql_test "supabase/tests/rpc_mesa_disponibles_excluye_rechazado_p195.sql"
run_sql_test "supabase/tests/rpc_mesa_correccion_primer_lote_p196.sql"
run_sql_test "supabase/tests/rpc_asesor_inbox_estado_efectivo_p197.sql"
run_sql_test "supabase/tests/rpc_mesa_cambio_revision_estado_efectivo_p198.sql"
run_sql_test "supabase/tests/rpc_mesa_disponibles_trabajo_accionable_p199.sql"
run_sql_test "supabase/tests/rpc_mesa_disponibles_todo_accionable_p206.sql"
run_sql_test "supabase/tests/rpc_mesa_disponibles_nuevos_correcciones_p207.sql"
run_sql_test "supabase/tests/rpc_mesa_disponibles_incluye_actualizaciones_p207_1.sql"
run_sql_test "supabase/tests/rpc_mesa_disponibles_excluye_pago_concasa_p207_2.sql"
run_sql_test "supabase/tests/rpc_mesa_cambios_excluye_firmados_p207_3.sql"
run_sql_test "supabase/tests/rpc_agenda_daily_cap_p208.sql"
run_sql_test "supabase/tests/rpc_p212_activate_guard.sql"
run_sql_test "supabase/tests/rpc_agenda_firmas_daily_cap_off_p212.sql"
run_sql_test "supabase/tests/rpc_agenda_firmas_daily_cap_p212.sql"
run_sql_test "supabase/tests/rpc_agenda_firmas_concurrency_p212.sql"
run_sql_test "supabase/tests/rpc_asesor_correccion_estado_efectivo_p201.sql"
run_sql_test "supabase/tests/rpc_asesor_mesa_correccion_latest_episode_p202.sql"
run_sql_test "supabase/tests/rpc_asesor_inbox_rechazo_operativo_p204a.sql"
run_sql_test "supabase/tests/rpc_asesor_reprecal_inbox_p183.sql"
run_sql_test "supabase/tests/rpc_editor_inbox_p186.sql"
run_sql_test "supabase/tests/rpc_agenda_sheet_manual_occupancy_p162.sql"
run_sql_test "supabase/tests/admin_stage_history_calibrated_p163.sql"
run_sql_test "supabase/tests/rpc_agenda_sheet_apply_operational_p170.sql"
run_sql_test "supabase/tests/rpc_agenda_contingencia_p172.sql"
run_sql_test "supabase/tests/rpc_agenda_sheet_red_color_veto_p173.sql"

run_sql_test "supabase/tests/rpc_admin_buscar_nss_p177.sql"
run_sql_test "supabase/tests/rpc_admin_search_cliente_expedientes_p182.sql"
run_sql_test "supabase/tests/rpc_agenda_sheet_effective_result_p180.sql"
run_sql_test "supabase/tests/rpc_bernardo_ops_p165.sql"
run_sql_test "supabase/tests/rpc_vigencia_documental_p211.sql"
run_sql_test "supabase/tests/rpc_vigencia_documental_p211_cert_final.sql"
# P212 ON-mode tests may commit enabled=true via implicit DDL; restore INSTALL OFF.
PGPASSWORD="$DB_PASSWORD" psql -v ON_ERROR_STOP=1 \
  -h "$DB_HOST" -p "$DB_PORT" -U "$DB_USER" -d "$DB_NAME" \
  -c "UPDATE public.agenda_firmas_daily_cap_contract
        SET enabled = FALSE, effective_from = NULL, enabled_at = NULL,
            note = 'test-sql: restore INSTALL OFF', updated_at = NOW()
        WHERE singleton;"

echo "SQL tests: ALL PASSED"
